### ISSUE TITLE
test discovery in NB nano

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#135] opened 2019-03-05 15:46 UTC
needs https://github.com/mF2C/mF2C/issues/99

**Comment by zeineb-rejiba** [comment] 2019-03-29 13:25
Created a new discovery image for the microagent available at:
https://cloud.docker.com/u/mf2c/repository/docker/mf2c/discovery-microagent

A Raspberry Pi with an external wireless interface was used for testing. So, wlan1 (the external one) is passed as an environment variable in the Dockerfile by default. 

Then, when the container is started, a python script will be run to trigger the scan, and if it finds a leader it connects to it (using wlan1).

The following docker-compose.yml can be used for testing:
`version: '3'
services:

  ################## Resource Manager ##################
  
  discovery:
     image: mf2c/discovery-microagent:1.0
     restart: on-failure
     expose:
       - 46040
     network_mode: host
     cap_add :
       - NET_ADMIN
  
  ######################################################`

**Comment by zeineb-rejiba** [comment] 2019-04-03 15:24
A new docker image, tagged 2.0,  has been pushed and is available at: https://cloud.docker.com/u/mf2c/repository/docker/mf2c/discovery-microagent 

This new image adds support for vpn connection if no leader has been found after the first scan attempt.

The following docker-compose.yml can be used for testing:
`version: '3'
services:

################## Resource Manager ##################

discovery:
image: mf2c/discovery-microagent:2.0
restart: on-failure
expose:
- 46040
network_mode: host
cap_add :
- NET_ADMIN
volumes:
- path/to/openvpn/config/file:/discovery/client.ovpn

######################################################`

**Comment by cjdcordeiro** [comment] 2019-04-04 15:21
@zeineb-rejiba , I'm testing this and found the following:
 - it reports `wlan1 does not exist! Exiting...`, but keeps running. 
    - at the same time, if no vpn file is provided, it just stays there...it should throw an exception and exit, otherwise it will be a zombie containers
    - if a vpn config file is provided, the same happens

**Comment by zeineb-rejiba** [comment] 2019-04-05 09:00
Please try again with the new image. 

Also note that I'm having the following error with openvpn (config file correctly provided):
Fri Apr  5 08:46:08 2019 disabling NCP mode (--ncp-disable) because not in P2MP client or server mode\nOptions error: You must define TUN/TAP device (--dev)\nUse --help for more information.

**Comment by cjdcordeiro** [comment] 2019-04-05 09:49
have a look at this: https://github.com/mje-nz/rpi-docker-openvpn/blob/master/Dockerfile

this is the image I've used. You need to setup the interface that is going to be used for the vpn. They do that in `bin/ovpn_run`

just try to adapt your's accordingly

**Comment by zeineb-rejiba** [comment] 2019-04-09 14:07
yes, working following the intstructions in that github repo. 

Also added "--daemon" option for starting openvpn smoothly from the python script. This is version 4.0 in docker hub.

**Comment by cjdcordeiro** [comment] 2019-06-26 10:01
@jjensenral how can we use your VPN client here?

**Comment by cjdcordeiro** [comment] 2019-06-28 05:40
thanks @jjensenral . Can you please build and publish the image into Docker hub? So, don't you need the CA and CAU? those do not have defaults.

@zeineb-rejiba once the image is published, can you use it in your code?

**Comment by zeineb-rejiba** [comment] 2019-06-28 10:12
@cjdcordeiro I can use the client.ovpn file it is generating. (Provided that it's specified in the volumes in the docker-compose)

**Comment by jjensenral** [comment] 2019-06-28 10:37
@zeineb-rejiba The default location for the ovpn file is /pkidata/client.ovpn.
I was going to integrate the script that bootstraps this into mf2c-entrypoint.sh (so will do a PR); the script then launches the VPN client
The client credential would already be there for a full agent but the script can call the CA if it isn't.

**Comment by syc17** [comment] 2019-06-28 10:49
The Cau-client stores the cert to /pkidata AFTER getting it from the CA (via the CAU).  So it depends on when you use the VPN, if it is AFTER the discovery, authen and categorisation process, then it should be there.

S

**Comment by cjdcordeiro** [comment] 2019-06-28 10:58
@zeineb-rejiba it is easier for you to simply deploy @jjensenral 's container and forget about it. Basically you don't need to handle the ovpn conf anymore... @jjensenral will auto generate it and start the client. All you need to do is launch his container

**Comment by jjensenral** [comment] 2019-06-28 11:07
Either way, I have updated the microagent Dockerfile and scripts into the 'stfc' branch but not created a pull request yet.
To avoid confusion, please note that there is an hub image for the server (mf2c/vpnserver) but not for the client because a container that only contains a vpn client is only useful for testing,

**Comment by cjdcordeiro** [comment] 2019-06-28 11:18
@jjensenral no you don't.

I think you are getting confused. the steps are:

1. your vpn client needs to be built into a Docker image (for arm and x86), and published into https://cloud.docker.com/u/mf2c/repository/list

2. since all it is required is to `docker run --cap-add=NET_ADMIN -d <your_vpn_client>:arm`, @zeineb-rejiba will edit her discovery, and instead of receiving the ovpn as an argument, she will simply share the Docker socket with her container, and when it's time, launch yours, with the command above

3. I'll then take her image and adjust the mf2c docker-compose-microagent

**Comment by jjensenral** [comment] 2019-06-28 11:38
Hey, if that's what you wanted, no problem; all you'd have to do is let me know.
I've uploaded the client image (for x86) to mf2c/vpnclient:latest
@zeineb-rejiba Let me know if it works as described and I can build the arm one

**Comment by zeineb-rejiba** [comment] 2019-06-28 11:59
@jjensenral that'll work, yes.
@cjdcordeiro one more clarification. The intention would be to run Jens's container as soon as I start mine? Or only when the discovery was not able to find leaders?

**Comment by cjdcordeiro** [comment] 2019-06-28 12:31
@zeineb-rejiba good question...let's say only when the discovery was not able to find leaders?

**Comment by jjensenral** [comment] 2019-06-28 12:42
FYI there's now also a mf2c/vpnclient:arm image; it is built on the arm32v7 port of Alpine.

**Comment by zeineb-rejiba** [comment] 2019-06-28 12:52
@cjdcordeiro yes, I'll do that.

**Comment by zeineb-rejiba** [comment] 2019-07-08 13:55
@cjdcordeiro Done. ==>mf2c/discovery-microagent:4.1

**Comment by cjdcordeiro** [comment] 2019-07-10 11:56
@zeineb-rejiba how do simply remove the ```volumes:
path/to/openvpn/config/file:/discovery/client.ovpn``` from the yaml file and start it?

**Comment by zeineb-rejiba** [comment] 2019-07-10 12:15
not sure I got your question @cjdcordeiro .
`volumes: path/to/openvpn/config/file:/discovery/client.ovpn` should be removed from the yaml file. Instead, `volumes: /var/run/docker.sock:/var/run/docker.sock` should be included to be able to launch the vpn container from the discovery container.

**Comment by zeineb-rejiba** [comment] 2019-08-16 09:49
Latest versions: `mf2c/discovery-microagent:latest` and `mf2c/discovery-microagent:4.2` 
Can be run as:
`docker run -it --network="host" --cap-add=NET_ADMIN -v /var/run/docker.sock:/var/run/docker.sock  mf2c/discovery-microagent:latest`

The output looks like the following:
```
[Discovery] wlan1 does not exist!
[Discovery] Connecting to VPN with the following parameters: 

{'cap_add': ['NET_ADMIN'],
 'environment': ['VPN_DAEMON=FALSE',
                 'CA_ENDPOINT=https://213.205.14.13:54443/certauths/rest/it2untrustedca'],
 'extra_hosts': {'vpnserver': '213.205.14.13'},
 'image': 'mf2c/vpnclient:1.1.0arm',
 'labels': {'mf2c.agent.type': 'microagent', 'mf2c.component': 'True'},
 'network_mode': 'host',
 'volumes': {'pkidata': {'bind': '/pkidata', 'mode': 'rw'}}}


[VPN Client] INFO Credentials ready; running credentials checks
[VPN Client] server.crt: OK
[VPN Client] RSA key ok
[VPN Client] writing RSA key
[VPN Client] Files pubkey1.pem and pubkey2.pem are identical
[VPN Client] INFO Credentials checks passed, creating OVPN
[VPN Client] INFO OVPN created; launching client
[VPN Client] Wed Aug 14 14:22:57 2019 OpenVPN 2.4.7 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  5 2019
[VPN Client] Wed Aug 14 14:22:57 2019 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
[VPN Client] Wed Aug 14 14:22:57 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]213.205.14.13:1194
[VPN Client] Wed Aug 14 14:22:57 2019 UDP link local: (not bound)
[VPN Client] Wed Aug 14 14:22:57 2019 UDP link remote: [AF_INET]213.205.14.13:1194
[VPN Client] Wed Aug 14 14:22:57 2019 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1541', remote='link-mtu 1542'
[VPN Client] Wed Aug 14 14:22:57 2019 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
[VPN Client] Wed Aug 14 14:22:57 2019 [CN] Peer Connection Initiated with [AF_INET]213.205.14.13:1194
[VPN Client] Wed Aug 14 14:22:59 2019 TUN/TAP device tun0 opened
[VPN Client] Wed Aug 14 14:22:59 2019 /sbin/ip link set dev tun0 up mtu 1500
[VPN Client] Wed Aug 14 14:22:59 2019 /sbin/ip addr add dev tun0 192.168.255.10/24 broadcast 192.168.255.255
[VPN Client] Wed Aug 14 14:22:59 2019 NOTE: unable to redirect default gateway -- VPN gateway parameter (--route-gateway or --ifconfig) is missing
[VPN Client] Wed Aug 14 14:22:59 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
[VPN Client] Wed Aug 14 14:22:59 2019 Initialization Sequence Completed
```
To retrieve the IP address, run the following command:
`docker exec -it mf2c_discovery_container_name python get_ip_addr.py`

**Comment by jjensenral** [comment] 2019-08-19 08:16
Hi @zeineb-rejiba I was really waiting for Souvik to report on the testing of the agent version, but I have built a mf2c/vpnclient1.1.1arm which is the next version, with the API we discussed on slack

**Comment by zeineb-rejiba** [comment] 2019-08-19 13:19
@jjensenral Besides the version number, any other changes in the parameters, compared to the ones shown in my comment above?

**Comment by jjensenral** [comment] 2019-08-20 08:50
Hi @zeineb-rejiba No change in parameters in `vpnclient:1.1.1arm`. The `VPN_DAEMON` is now obsolete but is ignored (it was designed to accommodate different ways of integrating it)

**Comment by zeineb-rejiba** [comment] 2019-08-20 10:31
FYI, I released a new image `mf2c/discovery-microagent:4.3` to accommodate this change, in addition to adding further checks (such as the existence of an internet connection). It is run the same way as before. 

The output looks like the following:
```
[Discovery] wlan1 does not exist!
[Discovery] No internet connection available! Unable to connect to the VPN.


[Discovery] wlan1 does not exist!
[Discovery] No internet connection available! Unable to connect to the VPN.


[Discovery] wlan1 does not exist!
[Discovery] No internet connection available! Unable to connect to the VPN.


[Discovery] wlan1 does not exist!
[Discovery] Connecting to VPN with the following parameters: 

{'cap_add': ['NET_ADMIN'],
 'environment': ['VPN_DAEMON=FALSE',
                 'CA_ENDPOINT=https://213.205.14.13:54443/certauths/rest/it2untrustedca'],
 'extra_hosts': {'vpnserver': '213.205.14.13'},
 'image': 'mf2c/vpnclient:1.1.1arm',
 'labels': {'mf2c.agent.type': 'microagent', 'mf2c.component': 'True'},
 'network_mode': 'host',
 'volumes': {'pkidata': {'bind': '/pkidata', 'mode': 'rw'}}}


[VPN Client] INFO Credentials ready; running credentials checks
[VPN Client] server.crt: OK
[VPN Client] RSA key ok
[VPN Client] writing RSA key
[VPN Client] Files pubkey1.pem and pubkey2.pem are identical
[VPN Client] INFO Credentials checks passed, creating OVPN
[VPN Client] INFO OVPN created; launching client


[Discovery] wlan1 does not exist!
[Discovery] Already connected to VPN!


[Discovery] wlan1 does not exist!
[Discovery] Already connected to VPN!


[Discovery] Scan attempt #  1
[Discovery] Number of found leaders = 1
Failed to connect to non-global ctrl_ifname: wlan1  error: No such file or directory
[Discovery] Successfully associated with leader!
[Discovery] Getting IP address...
[Discovery] IP address of wlan1 = 192.168.7.163


[Discovery] Already associated with leader!


[Discovery] Already associated with leader!


[Discovery] Already associated with leader!
^C[Discovery] Interrupted
```

**Comment by jjensenral** [comment] 2019-08-20 10:37
The VPN stuff looks OK; there is slightly less output in this version. Note it's the one with the API. Having just said that there are no changes, you might want to remap the `vpnclient` container's port, as in (say) 40013:80, just to get it off port 80.
I noticed your wlan address is 192.168.7.163; the VPN uses 192.168.255.0/24, so I presume they are unlikely to overlap.

**Comment by zeineb-rejiba** [comment] 2019-08-20 11:02
ok, I added the port mapping. 
Yes, I am using192.168.7.0/24 for the leader wlan.

**Comment by jjensenral** [comment] 2019-08-20 11:51
OK, cool; so the network addresses don't overlap at all. The port mapping is just there to get the API endpoint off port 80, which is usually overloaded. Remember you can query the status by doing an HTTP GET request to `/api/get_vpn_ip` (it's HTTP, not HTTPS because it's a read-only endpoint on the Docker private network.)

**Comment by zeineb-rejiba** [comment] 2019-09-16 08:41
I could query the container using the get_vpn_ip API call (also based on tun0 I guess).

**Comment by cjdcordeiro** [comment] 2019-09-16 10:50
yes it would be better if you could call the API instead.

but is the vpnclient providing the tun0 IP via the API as well? (@jjensenral ) hopefully it knows which interface has been set and provides the right IP...

**Comment by zeineb-rejiba** [comment] 2019-09-16 14:13
I have made a tentative update based on that API call (pending @jjensenral reply)
Then, when I am in a situation where I have to "terminate" the vpnclient container, shall I also remove the volumes associated with it?

**Comment by zeineb-rejiba** [comment] 2019-09-18 14:29
So @cjdcordeiro , @jjensenral suggests to check that the vpnclient is working properly by pinging the vpn server (192.168.255.1). I tested this approach and it works, too. 
Just let me know which one do you prefer, the ping-based or the REST call-based.

**Comment by cjdcordeiro** [comment] 2019-09-18 15:09
@zeineb-rejiba as you wish. The ping means that your code needs to know the IP of the VPN server, which can change, so as long as you account for that...

**Comment by zeineb-rejiba** [comment] 2019-09-19 14:11
Went with the REST call option. The fix is in `mf2c/discovery-microagent:4.4` .

**Comment by jjensenral** [comment] 2019-09-24 10:39
I'll add a ping feature into VPN client; in which case you find out the status by querying the API - it will update every ${PING_INTERVAL} seconds. I will also add a timestamp of sorts to the status message.
Meanwhile I noticed the main d-c file has a reference to 1.1.0 which is the last version *without* the API. I suggest that I commit 1.1.1 before submitting 1.1.2.

**Comment by zeineb-rejiba** [comment] 2019-10-01 14:48
@cjdcordeiro FYI `mf2c/discovery-microagent:4.5` (also `mf2c/discovery-microagent:latest` ) takes into account the changes made by @jjensenral in `mf2c/vpnclient1.1.2arm`.

**Closed** 2019-10-16 13:17 UTC
Labels: MICROAGENT, next
